#!/bin/bash

toplevel_directory="$(git rev-parse --show-cdup)"
[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; exit 1; }

find .git_externals -type l | while read gitdir; do
    if [ -d $gitdir ]; then
	pushd $gitdir
	echo "Dir to update:" $gitdir
        svn update
	popd
    fi
done
